### ISSUE TITLE
Create tests for PetType

### ISSUE THREAD

**Issue by redxzeta** [redxzeta/Awesome-Adoption#201]
- [ ] create `petType.test.js` in `__tests__` folder in `pets`
- [ ] create test cases for the zip code could be like invalid zipcode expect disabled button

**Comment by Akku2016** [comment]
hi, i am doing first time this one  I tried but little bit difficult for me because code i can write
 this is test case I thought this one i could do . i tried like this

import React from 'react';
import { render, screen, cleanup} from "@testing-library/react";
 
 import Search from "../Search";
 afterEach(cleanup);
test('should render zipcode disabled', () =>{
  const {getByTestId}= render(<Search />);
   
   expect(getByTestId('check')).toBeDisabled()
});
